name: Node.js package
on:
  push:
    branches:
      - master
env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  test-and-publish:
    runs-on: ubuntu-latest
    timeout-minutes: 4
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '14.x'
    - run: npm install
    - run: npm test
    - uses: JS-DevTools/npm-publish@v1
      with:
        token: ${{ env.NPM_TOKEN }}